from erarigilo.util import *
from .mistaker import *

generate_sampling_prep_generator = ChoiceSamplingWordSetConditionedTokenWiseGenerator(PrepWordConditionedChoiceSamplingCaseFittingTokenWiseMistaker)
generate_replacing_prep_generator = ReplacingTokenWiseGenerator(PrepWordConditionedReplacingCaseFittingTokenWiseMistaker)

generate_sampling_mark_generator = ChoiceSamplingWordSetConditionedTokenWiseGenerator(MarkWordConditionedChoiceSamplingCaseFittingTokenWiseMistaker)
generate_replacing_mark_generator = ReplacingTokenWiseGenerator(MarkWordConditionedReplacingCaseFittingTokenWiseMistaker)

generate_sampling_agent_generator = ChoiceSamplingWordSetConditionedTokenWiseGenerator(AgentWordConditionedChoiceSamplingCaseFittingTokenWiseMistaker)
generate_replacing_agent_generator = ReplacingTokenWiseGenerator(AgentWordConditionedReplacingCaseFittingTokenWiseMistaker)

generate_sampling_pcomp_generator = ChoiceSamplingWordSetConditionedTokenWiseGenerator(PcompWordConditionedChoiceSamplingCaseFittingTokenWiseMistaker)
generate_replacing_pcomp_generator = ReplacingTokenWiseGenerator(PcompWordConditionedReplacingCaseFittingTokenWiseMistaker)

generate_sampling_dative_generator = ChoiceSamplingWordSetConditionedTokenWiseGenerator(DativeWordConditionedChoiceSamplingCaseFittingTokenWiseMistaker)
generate_replacing_dative_generator = ReplacingTokenWiseGenerator(DativeWordConditionedReplacingCaseFittingTokenWiseMistaker)

generate_sampling_advmod_generator = ChoiceSamplingWordSetConditionedTokenWiseGenerator(AdvmodWordConditionedChoiceSamplingCaseFittingTokenWiseMistaker)
generate_replacing_advmod_generator = ReplacingTokenWiseGenerator(AgentWordConditionedReplacingCaseFittingTokenWiseMistaker)

